/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e7e2da",
        "surface-variant": "#e7e2da",
        "outline-variant": "#c3c9af",
        "on-error": "#ffffff",
        "on-primary-container": "#547400",
        "secondary": "#5f5e5e",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#e5e2e1",
        "on-secondary-container": "#656464",
        "tertiary-fixed": "#f5dbf1",
        "error": "#ba1a1a",
        "on-primary-fixed": "#141f00",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#474646",
        "surface": "#fef9f1",
        "on-tertiary-fixed": "#261626",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#374e00",
        "secondary-fixed": "#e5e2e1",
        "inverse-surface": "#32302b",
        "surface-tint": "#4a6700",
        "on-background": "#1d1c17",
        "inverse-primary": "#a1d820",
        "tertiary-fixed-dim": "#d8bfd5",
        "inverse-on-surface": "#f5f0e8",
        "primary": "#4a6700",
        "tertiary": "#6c586b",
        "surface-container-high": "#ece8e0",
        "surface-container": "#f2ede5",
        "outline": "#737a63",
        "tertiary-container": "#ffe4fb",
        "on-tertiary-fixed-variant": "#534153",
        "primary-fixed-dim": "#a1d820",
        "primary-container": "#c5ff4a",
        "surface-dim": "#ded9d2",
        "surface-bright": "#fef9f1",
        "on-tertiary-container": "#786477",
        "primary-fixed": "#bcf540",
        "error-container": "#ffdad6",
        "surface-container-low": "#f8f3eb",
        "on-secondary-fixed": "#1c1b1b",
        "on-error-container": "#93000a",
        "background": "#fef9f1",
        "on-surface-variant": "#434935",
        "secondary-fixed-dim": "#c8c6c5",
        "on-surface": "#1d1c17",
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
